apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: argocd
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: argocd-cluster-role
  apiGroup: rbac.authorization.k8s.io
