apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: python-flask-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5000
  type: {{ .Values.service.type }}
